name: .NET Core Unit Tests

on: [push]
    
jobs:
  build_and_test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1
      - name: Build with dotnet
        run: dotnet build ./NumericConverter.sln --configuration Release
      - name: Test with dotnet
        run: dotnet test ./NumericConverter.sln --configuration Release 
